// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sparse_gaussian_kernel_cpp
List sparse_gaussian_kernel_cpp(IntegerVector i, IntegerVector j, NumericMatrix coords, double bandwidth);
RcppExport SEXP _SEMA_sparse_gaussian_kernel_cpp(SEXP iSEXP, SEXP jSEXP, SEXP coordsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_gaussian_kernel_cpp(i, j, coords, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// normalize_sparse_weights
List normalize_sparse_weights(IntegerVector i, IntegerVector j, NumericVector weights, int nrow);
RcppExport SEXP _SEMA_normalize_sparse_weights(SEXP iSEXP, SEXP jSEXP, SEXP weightsSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_sparse_weights(i, j, weights, nrow));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SEMA_sparse_gaussian_kernel_cpp", (DL_FUNC) &_SEMA_sparse_gaussian_kernel_cpp, 4},
    {"_SEMA_normalize_sparse_weights", (DL_FUNC) &_SEMA_normalize_sparse_weights, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SEMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
