# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_gaussian_kernel_cpp <- function(i, j, coords, bandwidth) {
    .Call(`_SEMA_sparse_gaussian_kernel_cpp`, i, j, coords, bandwidth)
}

normalize_sparse_weights <- function(i, j, weights, nrow) {
    .Call(`_SEMA_normalize_sparse_weights`, i, j, weights, nrow)
}

